version: "3"
services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - myredisstorage:/data


  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3305:3306"
    environment:
      "MYSQL_DATABASE": "marketstorage"
      "MYSQL_ROOT_PASSWORD": "wordpass"
    volumes:
      - mysqlstorage:/var/lib/mysql
    

  app:
    container_name: smallmarket-app
    restart: always
    build: .
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"
    env_file: ./.env

volumes:
  mysqlstorage:
  myredisstorage:
    


  